server:
  port: 8085
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
#    context-path: /home

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: 'postgres'
    password: '0'
    url: 'jdbc:postgresql://localhost:5432/hh'
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties.hibernate:
      javax:
        cache:
          uri: classpath:ehcache.xml
      show_sql: true
      format_sql: true
#      generate_statistics: true # not production //only dev
      cache:
        use_query_cache: true
        use_second_level_cache: true
        region:
          factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
#    org.hibernate.cache.spi.support.AbstractReadWriteAccess: trace
#    //todo https://stackoverflow.com/questions/31585698/spring-boot-jpa2-hibernate-enable-second-level-cache
